version: "3.8"
services: 
  backend: 
      build: ./LetsGooooo
      ports:
        - "9000:9000"
      volumes: 
          - "./LetsGooooo:/code/LetsGooooo"
      command: "revel run -a ."
        

  mysql: 
      command: "mysqld  --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
      environment: 
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=LetsGo
      image: "library/mysql:8"
      ports: 
        - "3306:3306"
      volumes: 
        - "db:/var/lib/mysql:cached"

volumes: 
  db: 
    driver: local